// vue/src/App.vue
<template>
    <DxCheckBox
        :value="null"
        text="Approve"
        hint="Approve"
        icon-size="25"
        @value-changed="onValueChanged"
    />
</template>

<script>
import 'devextreme/dist/css/dx.light.css';
import { DxCheckBox } from 'devextreme-vue/check-box';
import notify from "devextreme/ui/notify";

export default {
    components: {
        DxCheckBox
    },
    methods: {
        onValueChanged(e) {
            if (e.value) {
                notify("The CheckBox is checked", "success", 500);
            }
        }
    }
}
</script>

// react/src/App.js
import React, { useCallback } from "react";
import "devextreme/dist/css/dx.light.css";

import { CheckBox } from 'devextreme-react/check-box';
import notify from "devextreme/ui/notify";

function App() {
    const onValueChanged = useCallback((e) => {
        if (e.value) {
            notify("The CheckBox is checked", "success", 500);
        }
    }, []);
    
    return (
        <CheckBox 
            value={null}
            text="Approve"
            hint="Approve"
            iconSize="25"
            onValueChanged={onValueChanged}
        />
    );
}

export default App;
