// react/src/App.js
import React, { useCallback } from "react";
import "devextreme/dist/css/dx.light.css";

import { CheckBox } from 'devextreme-react/check-box';
import notify from "devextreme/ui/notify";

function App() {
    const onValueChanged = useCallback((e) => {
        if (e.value) {
            notify("The CheckBox is checked", "success", 500);
        }
    }, []);
    
    return (
        <CheckBox 
            value={null}
            enableThreeStateBehavior={true}
            text="Approve"
            hint="Approve"
            iconSize="25"
            onValueChanged={onValueChanged}
        />
    );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import notify from 'devextreme/ui/notify';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {
    onValueChanged(e: { value: any; }) {
        if (e.value) {
            notify("The CheckBox is checked", "success", 500);
        }
    }
}


<dx-check-box
    [value]="null"
    [enableThreeStateBehavior]="true"
    text="Approve"
    hint="Approve"
    iconSize="25"
    (onValueChanged)="onValueChanged($event)"
>
</dx-check-box>
